### PR TITLE
Build tools update, Swift 4.2 etc.

### LINKED ISSUE #9: flutter compass does not specify a swift version
it is giving me this error **" [!] Unable to determine Swift version for the following pods:
    - `flutter_compass` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod."**

I even updated my cocoa pods also did a pod install which gave me the same error .
I also changed the pod file and put the target swift version for flutter compass but still the issue is not resolved . Could you please look into that and help me asap.
ThankYou

### PR DESCRIPTION
**Pull request by ened**
This plugin is very simple & might benefit from scaling back to Objective C & Java instead of Swift & Kotlin. The build system implications & dependencies are extremely cumbersome to maintain.

This PR should also fix #9.

### CODE REVIEW

**Comment by ened** [comment]
Hi @hemanthrajv - WDYT?

**Comment by hemanthrajv** [comment]
Thanks for the PR @ened. I'll definitely consider scaling back sometime later in future.

**Comment by ened** [comment]
@hemanthrajv would you accept a PR?

**Comment by hemanthrajv** [comment]
I think, I already merged and published too.

**Comment by hemanthrajv** [comment]
Ofcourse, yes.

**Pull request merged**
