### PR TITLE
Add namespace in the build.gradle

### PR DESCRIPTION
**Pull request by SNNafi**
Add namespace in the build.gradle to resolve build error in gradle version 8

### CODE REVIEW

**Comment by PikPakPik** [comment]
Duplicate https://github.com/hemanthrajv/flutter_compass/pull/113

**Review by hasnainelahi — APPROVED** [review]
Could you kindly merge this code to the master branch? we really appreciate your efforts. Thank you!

**Comment by SNNafi** [comment]
@hasnainelahi , only maintainers can merge

**Comment by mrsrmn** [comment]
Why is this not being merged?

**Comment by larsien** [comment]
please merge !

**Comment by Anvarkangadiyil** [comment]
please merge

**Comment by DmitriySimonov** [comment]
please merge

**Comment by hemanthrajv** [comment]
Closed in favor of #113

**Pull request closed without merging**
