### PR TITLE
[FIX] Support newer Android version and AGP >=8.0.0 compatibility

### PR DESCRIPTION
**Pull request by PikPakPik**
AGP >= 8 need to specify a namespace (https://github.com/hemanthrajv/flutter_compass/issues/104)
We need to update the compileSdk version due to this error "resource android:attr/lStar not found" since Android 12 so update to support 14 and lower (https://github.com/hemanthrajv/flutter_compass/issues/112)

### CODE REVIEW

**Comment by zigapovhe** [comment]
@hemanthrajv Can this be merged please? 
@PikPakPik Thanks for your contribution!

**Review by zigapovhe — APPROVED** [review]

**Review by zigapovhe — APPROVED** [review]

**Comment by Lah123** [comment]
Can somewone please merge this and make the new version available? I cannot build my project without this change. I have to reference the git project of @PikPakPik to make it work.

**Comment by LGro** [comment]
It seem like transistorsoft/flutter_background_fetch/issues/376 also works here, at least after adding the following to `android/build.gradle` I got the official `flutter_compass` to build again:
```gradle
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") || project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}
```
I'm not confident I understand what is happening here exactly, does this adapt the toolchain version to be different for dependencies?

**Comment by mrsrmn** [comment]
when will this be merged? this is extremely important, i cant build my project

**Pull request merged**
