### PR TITLE
Replace kotlin implementation with Java

### PR DESCRIPTION
**Pull request by ened**
As proposed in #10, please find a java implementation for the Android side of the plugin.

### CODE REVIEW

**Comment by ened** [comment]
Started  https://github.com/ened/flutter_compass/commit/1007d34e61b3c1c4ea48f27d7ec9b1df97280b4e based on this PR.

**Comment by ened** [comment]
@hemanthrajv WDYT

**Comment by hemanthrajv** [comment]
Thanks for the PR :)

**Comment by ened** [comment]
@hemanthrajv thx for merging, please publish on pub when you get the chance.

**Comment by hemanthrajv** [comment]
Sure, will do 👍

**Pull request merged**
