### PR TITLE
Remove permission requests when iOS plugin is instantiated

### LINKED ISSUE #12: Plugin must not request permissions when instantiated
If at all, this should be requested when the user starts the scan.

Library users are encouraged to include a plugin like `permission_handler` to retrieve what is needed.

Will prepare a PR.

### PR DESCRIPTION
**Pull request by ened**
... this is a responsibility of the library user.

Added permission request to the example project, as well.

Fixes #12

### CODE REVIEW

**Comment by ened** [comment]
@hemanthrajv do not forget to publish on pub

**Comment by hemanthrajv** [comment]
Sure, just checking things. Seems Readme to be updated to inform users to
invoke permissions manually.

**Comment by ened** [comment]
@hemanthrajv ok. Can you handle the README?

**Comment by hemanthrajv** [comment]
Yeah, also example folder shows pub warnings on dry run, hope I'll be able
to handle later today.

**Pull request merged**
